name: 'Use Terraform Action'
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Azure Login
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az storage blob list --account-name tfstatestore12345 --container-name tfstatecontainer

      

    - name: List directory contents
      run: ls -al ./vnet
    

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2


    - name: Terraform Deploy to Azure
      uses: MKTHEPLUGG/deploy-tf-vrs@v3
      env:
        TF_LOG: DEBUG
      with:
        storage_account_name: 'tfstatestore12345'
        container_name: tfstatecontainer
        key: 'terraform.tfstate'
        resource_group_name: TerraformStateRG
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        working-directory: ./vnet
