name: 'Use Terraform Action'
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2


    - name: Terraform Deploy to Azure
      uses: MKTHEPLUGG/deploy-tf-vrs@v2
      with:
        storage_account_name: 'tfstatestore12345'
        container_name: $tfstatecontainer
        key: 'terraform.tfstate'
        resource_group_name: TerraformStateRG
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        working-directory: ./vnet
