name: 'Use Terraform Action'
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: set permissions
      shell: bash
      run: |
        chmod +x entrypoint.sh


    - name: Terraform Deploy to Azure
      uses: MKTHEPLUGG/deploy-tf-vrs@v1
      with:
        storage_account_name: 'tfstatestore12345'
        container_name: $tfstatecontainer
        key: 'terraform.tfstate'
        resource_group_name: TerraformStateRG
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        working-directory: ./vnet
